### PR TITLE
New Readme

### PR DESCRIPTION
**Pull request by statulr**
Then you can merge it to the main I can make you the documentation really soon I'll prolly get started on that sometime if you want :) I like OS projects

### CODE REVIEW

**Comment by rifsxd** [comment]
appreciate for the first PR but since i just saw the PR just now after making a lot of commits the README in your fork is outdated could you review the changes and make a updated PR? thank you

**Comment by rifsxd** [comment]
and nice minimal and sleak logo!

**Comment by statulr** [comment]
Just got back gonna do it now

**Comment by statulr** [comment]
Couldn't think of anything, I actually have a  better idea check your dms :P

**Pull request closed without merging**
